pool:
  vmImage: 'windows-2022'

steps:

- task: VSBuild@1
  displayName: build
  inputs:
    configuration: 'Release'
    msbuildArgs: '/restore'

- task: DotNetCoreCLI@2
  displayName: test
  inputs:
    command: 'test'
    nobuild: true